spring:
  data:
    neo4j:
      uri: bolt://120.27.63.202:7687
      username: neo4j
      password: tiger
    mongodb:
      host: 47.95.115.246
      port: 27017
      authentication-database: admin
      database: note
      username: root
      password: BaruHezf9[Labc



