spring:
  data:
    neo4j:
      uri: bolt://120.27.63.202:7687
      username: neo4j
      password: tiger
    mongodb:
      host: 47.95.115.246
      port: 27017
      authentication-database: admin
      database: note
      username: root
      password: BaruHezf9[Labc
  redis:
    host: 120.27.63.202
    port: 6379
    database: 0
    password: Sequ4YalfCahr
image:
  storage: /usr/local/static/images/
  system: linux
hosts: http://notegraph.cn


