spring:
  neo4j:
    uri: bolt://104.225.155.121:7687
    authentication:
      username: neo4j
      password: TaxhBoci7^Bebi
#    mongodb:
#      host: 104.225.155.121
#      port: 27017
#      authentication-database: admin
#      database: note
#      username: root
#      password: BaruHezf9[Labc
#  redis:
#    host: 104.225.155.121
#    port: 6379
#    database: 0
#    password: Sequ4YalfCahr
image:
  storage: /usr/local/static/images/
  system: linux
hosts: http://notegraph.cn


